FROM fedora:34

WORKDIR /root

RUN dnf -y upgrade --setopt=install_weak_deps=False && \
    dnf -y install --setopt=install_weak_deps=False \
      bash bzip2 curl file findutils git make nano patch pkgconfig python3-pip unzip which xz yasm && \
    pip install scons==4.1.0

CMD /bin/bash
