FROM fedora:31

WORKDIR /root

RUN dnf -y upgrade --setopt=install_weak_deps=False && \
    dnf -y install --setopt=install_weak_deps=False \
      bash bzip2 curl git make patch pkgconfig python3 scons unzip which xz

CMD /bin/bash
